### ISSUE TITLE
 Invalid path for option `install_script` in section, pkglist.sh` does not exist

### ISSUE THREAD

**Issue by Gavalakis** [mainsail-crew/crowsnest#186] opened 2023-10-02 15:11 UTC
### What happened

It is the third time I installed crowsnest in my system. Always after a few reboots an error occurs, the camera stops working and I get two error messages in mainsail. Even though I am kind of a noob with this stuff, I tried finding the suggested sh file and placing it in the correct path but still nothing.

### What did you expect to happen

Working live feed and no errors.

### How to reproduce

I do not know.

### Additional information

[crowsnest (3).log](https://github.com/mainsail-crew/crowsnest/files/12783863/crowsnest.3.log)

![image](https://github.com/mainsail-crew/crowsnest/assets/61183477/e33949e4-0947-4f4c-85c7-e94e1af19a88)

**Comment by mryel00** [comment] 2023-10-02 15:49
Duplicate of #156 

To fix it, just run:
```bash
rm -rf ~/crowsnest/tools/pkglist.sh
ln -sf ~/crowsnest/tools/libs/pkglist-rpi.sh ~/crowsnest/tools/pkglist.sh
```
You might have to fix your `log_path` inside crowsnest.conf too

**Closed** 2023-10-02 15:50 UTC
Labels: bug, duplicate
