### ISSUE TITLE
Error with camera-streamer during make build

### ISSUE THREAD

**Issue by Mautty97** [mainsail-crew/crowsnest#196] opened 2023-11-02 02:51 UTC
### What happened

When first running `make build` , as well as after running `make buildclean` and then `make build` I get this error at the end:
> -DUSE_RTSP -I/usr/include/liveMedia -I/usr/include/groupsock -I/usr/include/BasicUsageEnvironment -I/usr/include/UsageEnvironment  -DUSE_LIBDATACHANNEL -Ithird_party/libdatachannel/include -Ithird_party/libdatachannel/deps/json/include -c -o util/http/http.o util/http/http.c
util/ffmpeg/remuxer.c: In function ‘ffmpeg_remuxer_open’:
util/ffmpeg/remuxer.c:97:33: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
   97 |   AVInputFormat *input_format = av_find_input_format(remuxer->input_format);
      |                                 ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:92: util/ffmpeg/remuxer.o] Error 1
make[2]: *** Waiting for unfinished jobs....
rm device/buffer_lock.o device/v4l2/buffer.o output/http_hls.o device/camera/camera_output.o device/v4l2/buffer_list.o device/buffer_queue.o device/buffer.o device/camera/camera_decoder.o device/links.o cmd/list-devices/main.o device/v4l2/d                             ebug.o device/camera/camera_input.o device/v4l2/device_options.o output/http_ffmpeg.o device/camera/camera.o device/camera/camera_rescaller.o device/libcamera/fake_camera.o cmd/camera-streamer/main.o device/buffer_list.o device/camera/camera_debug.o util/http/http.o device/camera/camera_pipeline.o device/dummy/buffer_list.o output/http_jpeg.o cmd/camera-streamer/opts.o output/output.o device/v4l2/device_list.o device/device_list.o device/v4l2/device_media.o device/dummy/device.o device/dummy/dummy.o device/dummy/buffer.o cmd/camera-streamer/http.o device/camera/camera_isp.o device/v4l2/v4l2.o device/device.o device/v4l2/device.o output/http_h264.o
make[2]: Leaving directory '/home/pi/crowsnest/bin/camera-streamer'
make[1]: *** [Makefile:62: all] Error 2
make[1]: Leaving directory '/home/pi/crowsnest/bin/camera-streamer'
make: *** [Makefile:23: build] Error 2

![image](https://github.com/mainsail-crew/crowsnest/assets/4841666/74bbe2c7-7ff6-4742-98ad-26d2a9823a3d)

### What did you expect to happen

The `make build` to complete successfully

### How to reproduce

This happens anytime I run `make build`

### Additional information

RPi 3b running Raspberry Pi OS Lite (32 bit)

crowsnest.log output (It just repeats)
> [11/02/23 02:31:25] crowsnest: Version: v4.0.4-6-g767c53a
[11/02/23 02:31:25] crowsnest: Prepare Startup ...
[11/02/23 02:31:25] crowsnest: INFO: Host information:
[11/02/23 02:31:25] crowsnest: Host Info: Distribution: Raspbian GNU/Linux 12 (bookworm)
[11/02/23 02:31:25] crowsnest: Host Info: Kernel: Linux 6.1.0-rpi4-rpi-v7 armv7l
[11/02/23 02:31:25] crowsnest: Host Info: Model:  Raspberry Pi 3 Model B Rev 1.2
[11/02/23 02:31:25] crowsnest: Host Info: Available CPU Cores: 4
[11/02/23 02:31:25] crowsnest: Host Info: Available Memory: 944088 kB
[11/02/23 02:31:25] crowsnest: Host Info: Diskspace (avail. / total): 49G / 59G
[11/02/23 02:31:25] crowsnest: INFO: Checking Dependencies
[11/02/23 02:31:25] crowsnest: Dependency: 'crudini' found in /usr/bin/crudini.
[11/02/23 02:31:25] crowsnest: Dependency: 'find' found in /usr/bin/find.
[11/02/23 02:31:25] crowsnest: Dependency: 'xargs' found in /usr/bin/xargs.
[11/02/23 02:31:25] crowsnest: Dependency: 'ustreamer' found in bin/ustreamer/ustreamer.
[11/02/23 02:31:25] crowsnest: Dependency: 'camera-streamer' not found. Exiting!
[11/02/23 02:31:31] crowsnest: crowsnest - A webcam Service for multiple Cams and Stream Services.
[11/02/23 02:31:31] crowsnest: Version: v4.0.4-6-g767c53a
[11/02/23 02:31:31] crowsnest: Prepare Startup ...
[11/02/23 02:31:31] crowsnest: INFO: Host information:
[11/02/23 02:31:31] crowsnest: Host Info: Distribution: Raspbian GNU/Linux 12 (bookworm)
[11/02/23 02:31:31] crowsnest: Host Info: Kernel: Linux 6.1.0-rpi4-rpi-v7 armv7l
[11/02/23 02:31:31] crowsnest: Host Info: Model:  Raspberry Pi 3 Model B Rev 1.2
[11/02/23 02:31:31] crowsnest: Host Info: Available CPU Cores: 4
[11/02/23 02:31:31] crowsnest: Host Info: Available Memory: 944088 kB
[11/02/23 02:31:31] crowsnest: Host Info: Diskspace (avail. / total): 49G / 59G
[11/02/23 02:31:31] crowsnest: INFO: Checking Dependencies
[11/02/23 02:31:31] crowsnest: Dependency: 'crudini' found in /usr/bin/crudini.
[11/02/23 02:31:31] crowsnest: Dependency: 'find' found in /usr/bin/find.
[11/02/23 02:31:31] crowsnest: Dependency: 'xargs' found in /usr/bin/xargs.
[11/02/23 02:31:31] crowsnest: Dependency: 'ustreamer' found in bin/ustreamer/ustreamer.
[11/02/23 02:31:31] crowsnest: Dependency: 'camera-streamer' not found. Exiting!
[11/02/23 02:31:37] crowsnest: crowsnest - A webcam Service for multiple Cams and Stream Services.
[11/02/23 02:31:37] crowsnest: Version: v4.0.4-6-g767c53a
[11/02/23 02:31:37] crowsnest: Prepare Startup ...
[11/02/23 02:31:37] crowsnest: INFO: Host information:
[11/02/23 02:31:37] crowsnest: Host Info: Distribution: Raspbian GNU/Linux 12 (bookworm)
[11/02/23 02:31:37] crowsnest: Host Info: Kernel: Linux 6.1.0-rpi4-rpi-v7 armv7l
[11/02/23 02:31:37] crowsnest: Host Info: Model:  Raspberry Pi 3 Model B Rev 1.2
[11/02/23 02:31:37] crowsnest: Host Info: Available CPU Cores: 4
[11/02/23 02:31:37] crowsnest: Host Info: Available Memory: 944088 kB
[11/02/23 02:31:37] crowsnest: Host Info: Diskspace (avail. / total): 49G / 59G
[11/02/23 02:31:37] crowsnest: INFO: Checking Dependencies
[11/02/23 02:31:37] crowsnest: Dependency: 'crudini' found in /usr/bin/crudini.
[11/02/23 02:31:37] crowsnest: Dependency: 'find' found in /usr/bin/find.
[11/02/23 02:31:37] crowsnest: Dependency: 'xargs' found in /usr/bin/xargs.
[11/02/23 02:31:37] crowsnest: Dependency: 'ustreamer' found in bin/ustreamer/ustreamer.
[11/02/23 02:31:37] crowsnest: Dependency: 'camera-streamer' not found. Exiting!
[11/02/23 02:31:43] crowsnest: crowsnest - A webcam Service for multiple Cams and Stream Services.
[11/02/23 02:31:43] crowsnest: Version: v4.0.4-6-g767c53a
[11/02/23 02:31:43] crowsnest: Prepare Startup ...
[11/02/23 02:31:43] crowsnest: INFO: Host information:
[11/02/23 02:31:43] crowsnest: Host Info: Distribution: Raspbian GNU/Linux 12 (bookworm)
[11/02/23 02:31:43] crowsnest: Host Info: Kernel: Linux 6.1.0-rpi4-rpi-v7 armv7l
[11/02/23 02:31:43] crowsnest: Host Info: Model:  Raspberry Pi 3 Model B Rev 1.2
[11/02/23 02:31:43] crowsnest: Host Info: Available CPU Cores: 4
[11/02/23 02:31:43] crowsnest: Host Info: Available Memory: 944088 kB
[11/02/23 02:31:43] crowsnest: Host Info: Diskspace (avail. / total): 49G / 59G
[11/02/23 02:31:43] crowsnest: INFO: Checking Dependencies
[11/02/23 02:31:44] crowsnest: Dependency: 'crudini' found in /usr/bin/crudini.
[11/02/23 02:31:44] crowsnest: Dependency: 'find' found in /usr/bin/find.
[11/02/23 02:31:44] crowsnest: Dependency: 'xargs' found in /usr/bin/xargs.
[11/02/23 02:31:44] crowsnest: Dependency: 'ustreamer' found in bin/ustreamer/ustreamer.
[11/02/23 02:31:44] crowsnest: Dependency: 'camera-streamer' not found. Exiting!

**Comment by mryel00** [comment] 2023-11-02 07:26
Duplicate of #188
Also you should run `sudo make install` for the initial installation, as it will still setup things after building the backends successfully.

**Closed** 2023-11-02 07:26 UTC
Labels: bug, duplicate
