### ISSUE TITLE
Function Brokenfocus never gets called

### ISSUE THREAD

**Issue by Obagunceiro** [mainsail-crew/crowsnest#232] opened 2024-01-14 02:41 UTC
### What happened

The brokenfocus function that should be executed to define the absolute focus is never called, when I look at the LOG, the following never appears: WARN: Detected 'brokenfocus' device. and then this function is not executed and my focus is always set to the webcam default, which in my case is 160, I can set the value for focus_absolute easily via SSH with the command: v4l2-ctl --set-ctrl=focus_absolute=200
. The problem is that whenever the crownest service is restarted, my webcam goes to default focus

### What did you expect to happen

I would expect the following message to appear: WARN: Detected 'brokenfocus' device, and for my absolute focus to be set to that of crownest.cfg

### How to reproduce

Configure v4l2 in crownest.cfg with the parameters focus_continuous_absolute=0 and focus_absolute=X
Using ustreamer (camera-streamer also doesn't set my focus)
Start the crownest service

### Additional information

[crowsnest.log](https://github.com/mainsail-crew/crowsnest/files/13930152/crowsnest.log)
![Screenshot_2](https://github.com/mainsail-crew/crowsnest/assets/138526117/ed85c65d-1acf-4c31-b7ed-8cf4812d4c31)

**Comment by mryel00** [comment] 2024-01-14 09:54
> The brokenfocus function that should be executed to define the absolute focus is never called

The `brokenfocus` function only executes, if it detecs that the settings are wrong after it got already set, as some devices got problems with settings it too early.
But this is a duplicate of the other issue you wrote in. Please don't do such things.

**Closed** 2024-01-14 09:58 UTC
Labels: bug, duplicate
